plugins:
  duplication:
    enabled: true
    config:
      languages:
      - typescript:
        mass_threshold: 50

  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrcjson
  
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
      - CUSTOM

  git-legal:
    enabled: true
  
  nodesecurity:
    enabled: true
